# Generated by Django 5.2.12 on 2026-03-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('file1', 'Файл 1'), ('file2', 'Файл 2'), ('file4', 'Файл 4 (обработанные)')], db_index=True, max_length=16)),
                ('point_index', models.PositiveIntegerField()),
                ('x_value', models.FloatField()),
                ('y_value', models.FloatField()),
                ('batch_id', models.CharField(db_index=True, default='default', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('source', 'point_index'),
                'constraints': [models.UniqueConstraint(fields=('source', 'batch_id', 'point_index'), name='uniq_source_batch_point_index')],
            },
        ),
    ]
