# Generated by Django 5.2.13 on 2026-05-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icp_stat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsedpoint',
            options={'ordering': ('source', 'temperature', 'point_index')},
        ),
        migrations.RemoveConstraint(
            model_name='parsedpoint',
            name='uniq_source_batch_point_index',
        ),
        migrations.AddField(
            model_name='parsedpoint',
            name='temperature',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='parsedpoint',
            constraint=models.UniqueConstraint(fields=('source', 'batch_id', 'temperature', 'point_index'), name='uniq_source_batch_temp_point_index'),
        ),
    ]
