# Generated by Django 5.2.13 on 2026-05-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icp_stat', '0002_alter_parsedpoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedpoint',
            name='mass_to_charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
