# Generated by Django 6.0.5 on 2026-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual input'), ('database', 'Database input')], max_length=16)),
                ('mode', models.CharField(max_length=16)),
                ('example_name', models.CharField(blank=True, max_length=128)),
                ('raw_input', models.TextField(blank=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('include_condensed', models.BooleanField(default=True)),
                ('include_ions', models.BooleanField(default=False)),
                ('feed_input', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
