# Generated by Django 6.0.5 on 2026-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equilibrium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcalculation',
            name='pressure_mpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcalculation',
            name='temperature_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcalculation',
            name='temperature_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcalculation',
            name='temperature_step',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
