# Generated by Django 6.0.5 on 2026-05-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equilibrium', '0002_savedcalculation_pressure_mpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcalculation',
            name='temperature_report',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
