# Generated by Django 6.0.5 on 2026-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equilibrium', '0003_savedcalculation_temperature_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcalculation',
            name='feed_basis',
            field=models.CharField(default='mole', max_length=16),
        ),
    ]
